name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 15.10
        uses: actions/setup-node@v1
        with:
          node-version: "15.10"
      - name: Install dependencies and then create docker image
        run: |
          npm install
        env:
          CI: true
      - name: Publish to GitLab Container Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: davidilie/projects
          registry: registry.gitlab.com
          username: DavidIlie
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          dockerfile: Dockerfile
          tags: dht-app
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Kubernetes
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout restart deploy dht-app -n dht-ro
